### ISSUE TITLE
Update payment settings to show LANDofDistraction on customer statements

### ISSUE THREAD

**Issue by ErinLOD** [Land-of-Distraction/LoD.com#11]
change what customers see on payment statements to LANDofDistraction

**Comment by briznad** [comment]
@ErinLOD do you have a screenshot or example email so I can better understand where the problematic site title shows up?

**Comment by ErinLOD** [comment]
i already did this, as you can see it's been moved to the done column💁🏼


Erin Frederick

erin@landofdistraction.com

858.531.2112


This email is  confidential. If you are not the intended recipient, any use, copying, disclosure, or distribution is  prohibited.  Please notify us immediately and delete this email from your computer systems. Unless this email is sent pursuant to an agreement between Distraction Wear Inc. or any of its affiliates, and the recipient, Distraction Wear Inc. and its affiliates do not provide any warranties, representations and conditions with respect to this email and its contents, and disclaim any such warranties, representations and conditions, express or implied. Distraction Wear Inc. and its affiliates do not assume any liability with respect to the accuracy or completeness of the information set out in this email, or for any use of, or inability to use any of the information set out in this email.  If you do not wish to receive any further emails from us, you may unsubscribe by replying “unsubscribe”.  You may also contact us in writing at the following address: stacey@landofdistraction.com<mailto:stacey@landofdistraction.com>

________________________________

**Comment by briznad** [comment]
Ah, I'm too slow.
