### ISSUE TITLE
(7/25) Add Japanese Retailers to Retailers page

### ISSUE THREAD

**Issue by ErinLOD** [Land-of-Distraction/LoD.com#13]
In a new (International) column we want to add the below Japanese Retailers:

For JAPAN distribution (starting 8/1) we should say:
 
 
ESTNATION Roppongi Hills
·        Location:
1&2F Hillside Keyakizaka Complex, Roppongi Hills
6-10-2 Roppongi, Minato-ku, Tokyo
106-0032

ESTNATION Fukuoka
·        Location:
2F Solaria Plaza
2-2-43 Tenjin Chuo-ku, Fukuoka-shi, Fukuoka
810-0001

ESTNATION Osaka
·        Location:
3F LUCUA 1100
3-1-3 Umeda, Kita-ku, Osaka-shi, Osaka
530-8558

ESTNATION Kyoto
·        Location:
3F Kyoto BAL
251 Yamazaki-cho, Kawaramachi-Dori Sanjo
Sagaru, Nakagyo-ku, Kyoto-shi, Kyoto
604-8032
 
Spick & Span (3 locations)
 
YURAKUCHO　２－５－１　ＬＵＭＩＮＥ２Ｆ　ＹＵＲＡＫＵＣＨＯ　ＣＨＩＹＯＤＡ－ＫＵ　ＴＯＫＹＯ
 
OSAKA　LUCUA IRE  3-1-3  UMEDA KITA-KU 　OSAKA-CITY OSAKA
 
NAGOYA 　３－６－１　ＬＡＣＨＩＣ３F　ＳＡＫＡＥ　ＮＡＫＡ－ＫＵ　ＮＡＧＯＹＡ－ＣＩＴＹ　ＡＩＣＨＩ

**Comment by ErinLOD** [comment]
Hey Brad, I gave this a go using the 'table' in the shopify page editor but it could probably look cleaner if done right

**Comment by briznad** [comment]
I updated the retailers page. It's now controlled via the Admin UI:
https://lod-production.myshopify.com/admin/themes/23540596780/editor#/pages/retailers

**Comment by ErinLOD** [comment]
Thanks, Brad! That looks MUCH better than my little hack
