### ISSUE TITLE
New/Addlt USOW Landing Page

### ISSUE THREAD

**Issue by ErinLOD** [Land-of-Distraction/LoD.com#15]
Want to duplicate this page: https://www.landofdistraction.com/pages/usow at a separate / unique URL ( maybe https://www.landofdistraction.com/pages/usowDM) so we can use it to track traffic from one marketing initiative specifically - would also like to replace the image of Danita pointing if possible

**Comment by briznad** [comment]
@ErinLOD do we have an alternative asset to replace the pointing img with?

**Comment by briznad** [comment]
@ErinLOD should the header nav link be updated to point to the new page or stay the same?

**Comment by ErinLOD** [comment]
The link in the header nave should stay as is / linked to the current page. 

On the hidden/new landing page I'd like to switch the danita pointing image to this Laverne Cox image:

 https://distractionwearusainc-my.sharepoint.com/:i:/g/personal/stacey_landofdistraction_com/EfoprSPld6JEhezCwl9rgCwBi4JbKxVUWkSEf-vjcs78nA?e=hvKyGo
