### ISSUE TITLE
Upgrade Shopify Checkout by July 25

### ISSUE THREAD

**Issue by ErinLOD** [Land-of-Distraction/LoD.com#16]
What do I have to do? 

Make changes to your checkout.liquid and checkout.scss.liquid files, test these changes, and then upgrade your checkout before July 25. Please note that upgrades may take a few days to complete, so give yourself enough time to plan, test and upgrade.
Begin the checkout upgrade process by visiting your Shopify Admin and adding /settings/checkout/checkout_upgrade to your URL.

What happens after July 25? 

If the checkout upgrade is not completed by July 25, then your checkout will be automatically upgraded to the standard, non-customized Shopify checkout. You will lose your checkout customizations

**Comment by briznad** [comment]
checkout has been updated, tested, and upgraded
