### ISSUE TITLE
sold out / selection of default size rule / notify me access

### ISSUE THREAD

**Issue by briznad** [Land-of-Distraction/LoD.com#6]
come up with solution for the null / default size selection / sold out / notify me when available - if an item has any available variations (size/color) the available options will be chosen by default

**Comment by briznad** [comment]
this can be seen at:
https://www.landofdistraction.com/products/freddy_blonde?variant=9869279952940

**Comment by ErinLOD** [comment]
Hey Brad, I'm seeing it skip size 0 and preselect 2 (the first available) so 👍🏼

I'm guessing the ability to select 0 / sold out sizes for Notify Me is a part 2 of this issues/fix

**Comment by briznad** [comment]
Yeah, I was going to create a separate issue for the ability to select
unavailable sizes.
